name = "MonteCarloGlauber"
uuid = "975a0a4c-3350-41ca-9a50-68f91c961bd0"
version = "1.0.0-DEV"
authors = ["Eduardo Grossi", "Andreas Kirchner"]

[deps]
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
DifferentiationInterface = "a0c0ee7d-e4b9-4e03-894e-1c5f64a51d63"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
FastGaussQuadrature = "442a2c76-b920-505d-bb47-c5924d526838"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
IterTools = "c8e1da08-722c-5040-9ed9-7db0dc04731e"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
OhMyThreads = "67456a42-1dca-4109-a031-0a68de7e3ad5"
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Rotations = "6038ab10-8711-5258-84ad-4b1120ba62dc"
SimpleNonlinearSolve = "727e6d20-b764-4bd8-a329-72de5adea6c7"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
DelimitedFiles = "1.9, 1.10, 1.11, 1.12"
DifferentiationInterface = "0.6, 0.7, 0.8"
Distributions = "0.25, 0.26"
FastGaussQuadrature = "1.1, 1.2"
HDF5 = "0.17, 0.18"
Interpolations = "0.15.1, 0.16, 0.17"
IterTools = "1.10"
LinearAlgebra = "1"
OhMyThreads = "0.7, 0.8, 1"
QuadGK = "2.11, 3, 4"
Random = "1"
Rotations = "1.7.1, 1.8"
SimpleNonlinearSolve = "2.1, 3"
SpecialFunctions = "2.5, 2.6"
StaticArrays = "1.9, 1.10"
Statistics = "1.11, 1.12"
StatsBase = "0.34, 0.35"
julia = "1.10 - 1.12"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
